import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "../styles/portfolio.css"

const studies = [
  { id: "ads-sdk", number: "01", eyebrow: "0 → 1 SDK infrastructure", title: <>Making an ads platform easy to <em>adopt.</em></>, context: "Advertising experiences needed to work across multiple Navi customer journeys without making every consuming team reinvent the integration or analytics layer.", stats: [["Result", "~60% lower partner onboarding effort"], ["Reliability", ">99% analytics event delivery"]], sections: [["Designed the integration once.", "I built a reusable React + TypeScript Web SDK that could be plugged into Personal Loans, AMC, and future journeys. It gave teams one consistent surface for rendering and event instrumentation."], ["Events were treated as product data.", "Analytics batching sent data roughly every five events or five seconds. Where appropriate, the SDK used sendBeacon to improve delivery during page lifecycle changes, with localStorage recovery to guard against event loss."], ["Infrastructure is a developer experience.", "The outcome was more than an SDK: it enabled a new advertising revenue stream while reducing integration work for the teams adopting it."]], dark: true },
  { id: "session-service", number: "02", eyebrow: "Sessions at scale", title: <>Faster auth, built for <em>volume.</em></>, context: "A session system based on UUIDs had an opportunity to become faster and more scalable. The redesign moved to JWT-backed session tokens supported by ElastiCache / Redis infrastructure.", stats: [["Latency", "20ms → 2ms"], ["Throughput", "~1.2M requests/min"]], sections: [["Move the hot path closer.", "The new approach used JWTs for the session-token model, with Redis / ElastiCache providing the supporting infrastructure. This cut unnecessary work from a frequently exercised path."], ["Frontend depth doesn’t end at the browser.", "Owning product quality often means crossing boundaries—into authentication, caching, API contracts, and operational performance."]] },
  { id: "funnel-optimization", number: "03", eyebrow: "Funnel optimization", title: <>Respect the <em>browser</em> to improve the funnel.</>, context: "Browser popup restrictions were creating a disruptive double-popup experience in a Personal Loan funnel. The solution had to respect a real user interaction rather than fight browser behavior.", stats: [["Experiment result", "Estimated ₹73 Cr/month uplift"], ["Method", "A/B tested"]], sections: [["Do the work before the click.", "I redesigned the sequence so relevant API work occurred earlier, and the popup was opened through a valid user-initiated action. The resulting experience used a single popup and no longer depended on browser-blocked behavior."], ["Product metrics live in implementation details.", "Browser APIs and interaction timing can sound like frontend minutiae. In a funnel, they can directly decide whether a customer completes a journey."]] },
  { id: "workflow-platform", number: "04", eyebrow: "Internal workflow platform", title: <>Make complex work feel <em>lighter.</em></>, context: "Complex operations tooling built with React Flow had high-latency paths affecting on-call teams and their ability to resolve issues quickly.", stats: [["Workflow speed", "8s → 2s"], ["Resolution time", "80–90% lower"]], sections: [["Performance for the people on the hook.", "I improved important workflows in a graph-based internal platform, reducing the time operators spent waiting for complex UI paths to complete."], ["Good internal tools compound.", "The improvements reduced on-call workload by roughly 40–50% and made resolution significantly faster—an example of the leverage I look for in product engineering."]] },
]

const CaseStudies = (_props: PageProps) => <>
  <a className="skip-link" href="#main-content">Skip to content</a>
  <nav className="nav" aria-label="Case study navigation"><a className="wordmark" href="/" aria-label="Suhail Malik home">SM<span>·</span></a><a className="nav-contact" href="/">← Back to portfolio</a></nav>
  <main className="case-page" id="main-content">
    <header className="case-hero"><p className="eyebrow">Selected engineering case studies</p><h1>How I turn product<br />constraints into <em>leverage.</em></h1><p>Concise technical stories: the context, the decisions I owned, and the outcome. Confidential product details are intentionally omitted.</p></header>
    {studies.map((study) => <article className={`case-study ${study.dark ? "dark-case" : ""}`} id={study.id} key={study.id}><div className="case-index">{study.number} / Navi</div><div className="case-title"><p className="eyebrow">{study.eyebrow}</p><h2>{study.title}</h2></div><div className="case-summary"><p>{study.context}</p><dl>{study.stats.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="case-body">{study.sections.map(([title, copy]) => <section key={title}><h3>{title}</h3><p>{copy}</p></section>)}</div></article>)}
  </main>
</>

export default CaseStudies
export const Head: HeadFC = () => <><title>Engineering case studies — Suhail Malik</title><meta name="description" content="Concise engineering case studies covering product constraints, technical decisions, and measurable outcomes." /><meta property="og:title" content="Engineering case studies — Suhail Malik" /><meta property="og:description" content="Technical decisions connected to measurable product outcomes." /><meta property="og:type" content="website" /><meta property="og:url" content="https://suhailmalik.dev/case-studies/" /><meta property="og:image" content="https://suhailmalik.dev/social-card.svg" /><meta name="twitter:card" content="summary_large_image" /><link rel="canonical" href="https://suhailmalik.dev/case-studies/" /><link rel="icon" href="/favicon.svg" type="image/svg+xml" /></>
