import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "../styles/portfolio.css"

const notes = [
  { id: "reliable-analytics", label: "Client-side infrastructure", title: "Reliable analytics is a product feature", lead: "If event data disappears during navigation, retries, or rough connections, the product team loses the evidence needed to make good decisions.", body: ["For a reusable Web SDK, I treated analytics as infrastructure rather than a callback every integration had to get right. Events were batched roughly every five events or five seconds, limiting unnecessary network work while keeping data fresh.", "Where a page was about to unload, sendBeacon offered a more resilient delivery path. Local storage recovery provided a second line of defense when an event could not be delivered immediately. The result was more than 99% event delivery without pushing reliability complexity onto every consuming team."] },
  { id: "browser-behavior", label: "Browser behavior", title: "The browser is part of the product constraint", lead: "A customer funnel can fail for a reason that looks small in a code review: when the browser decides an interaction was not initiated by a user.", body: ["A Personal Loan flow had a double-popup experience caused by browser restrictions. The right answer was not to work around the browser, but to make the sequence valid: prepare the required API work earlier and open the popup from a genuine user action.", "That change removed the disruptive second popup and let the journey behave predictably. An A/B test showed an estimated INR 73 Cr/month uplift. Implementation details are often product decisions in disguise."] },
  { id: "performance", label: "Systems thinking", title: "Performance earns its place when it removes friction at scale", lead: "A faster number matters when it changes what people can do next: customers finish a flow, an on-call engineer resolves an issue, or a team stops waiting.", body: ["Session infrastructure shifted from UUID-based handling to JWT tokens supported by ElastiCache and Redis. That moved latency from roughly 20ms to 2ms while operating at around 1.2 million requests per minute.", "The same principle shaped internal React Flow tooling: reducing key workflows from about eight seconds to two made the system less painful for the people operating it, contributing to lower on-call load and much faster resolution."] },
]

const Notes = (_props: PageProps) => <><a className="skip-link" href="#main-content">Skip to content</a><nav className="nav" aria-label="Notes navigation"><a className="wordmark" href="/" aria-label="Suhail Malik home">SM<span>·</span></a><a className="nav-contact" href="/">← Back to portfolio</a></nav><main className="notes-page" id="main-content"><header className="case-hero"><p className="eyebrow">Engineering notes</p><h1>Things I’ve learned<br />by building <em>close to the work.</em></h1><p>Short notes on product engineering, browser behavior, and systems that earn their complexity.</p></header><div className="note-articles">{notes.map(note => <article id={note.id} key={note.id}><p className="eyebrow">{note.label}</p><h2>{note.title}</h2><p className="note-lead">{note.lead}</p>{note.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</article>)}</div></main></>

export default Notes
export const Head: HeadFC = () => <><title>Engineering notes — Suhail Malik</title><meta name="description" content="Notes on product engineering, browser behavior, and systems by Suhail Malik." /><meta property="og:title" content="Engineering notes — Suhail Malik" /><meta property="og:description" content="Notes on product engineering, browser behavior, and systems." /><meta property="og:type" content="website" /><meta property="og:url" content="https://suhailmalik.dev/notes/" /><meta property="og:image" content="https://suhailmalik.dev/social-card.svg" /><meta name="twitter:card" content="summary_large_image" /><link rel="canonical" href="https://suhailmalik.dev/notes/" /><link rel="icon" href="/favicon.svg" type="image/svg+xml" /></>
